# Generated by Django 2.0.1 on 2018-01-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_options', models.CharField(choices=[('Retail', 'Retail'), ('Entertainment', 'Entertainment'), ('Food', 'Food'), ('Mobile Application', 'Mobile Application'), ('Sports', 'Sports'), ('Hardware', 'Hardware'), ('Other', 'Other'), ('Health', 'Health'), ('Social Platform', 'Social Platform'), ('Real estate', 'Real estate'), ('Automotive', 'Automotive'), ('Consumer Reporting Agency', 'Consumer Reporting Agency'), ('Telecommunications', 'Telecommunications'), ('Financial Services', 'Financial Services')], default='Retail', max_length=100)),
            ],
        ),
    ]
